import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';
import type * as s from './schema';

export type Organization = InferSelectModel<typeof s.organizations>;
export type User = InferSelectModel<typeof s.users>;
export type Membership = InferSelectModel<typeof s.memberships>;
export type OrgSettingsRow = InferSelectModel<typeof s.orgSettings>;
export type Company = InferSelectModel<typeof s.companies>;
export type NewCompany = InferInsertModel<typeof s.companies>;
export type Contact = InferSelectModel<typeof s.contacts>;
export type NewContact = InferInsertModel<typeof s.contacts>;
export type Campaign = InferSelectModel<typeof s.campaigns>;
export type CampaignStep = InferSelectModel<typeof s.campaignSteps>;
export type CampaignVariant = InferSelectModel<typeof s.campaignVariants>;
export type CampaignMembership = InferSelectModel<typeof s.campaignMemberships>;
export type Conversation = InferSelectModel<typeof s.conversations>;
export type Message = InferSelectModel<typeof s.messages>;
export type OutboundJob = InferSelectModel<typeof s.outboundJobs>;
export type Appointment = InferSelectModel<typeof s.appointments>;
export type PipelineDeal = InferSelectModel<typeof s.pipelineDeals>;
export type Activity = InferSelectModel<typeof s.activities>;
export type Task = InferSelectModel<typeof s.tasks>;
export type Notification = InferSelectModel<typeof s.notifications>;
export type PhoneNumber = InferSelectModel<typeof s.phoneNumbers>;
export type Qualification = InferSelectModel<typeof s.qualifications>;
export type AiSummary = InferSelectModel<typeof s.aiSummaries>;
export type AiPrompt = InferSelectModel<typeof s.aiPrompts>;
export type KnowledgeEntry = InferSelectModel<typeof s.knowledgeEntries>;
export type Objection = InferSelectModel<typeof s.objections>;
export type SuppressionEntry = InferSelectModel<typeof s.suppressionEntries>;

export type UserRole = (typeof s.userRoleEnum.enumValues)[number];
export type ProspectStatus = (typeof s.prospectStatusEnum.enumValues)[number];
export type CampaignStatus = (typeof s.campaignStatusEnum.enumValues)[number];
export type ConversationState = (typeof s.conversationStateEnum.enumValues)[number];
export type MessageStatus = (typeof s.messageStatusEnum.enumValues)[number];
export type MessageDirection = (typeof s.messageDirectionEnum.enumValues)[number];
export type MessageAuthor = (typeof s.messageAuthorEnum.enumValues)[number];
export type PipelineStage = (typeof s.pipelineStageEnum.enumValues)[number];
export type AppointmentStatus = (typeof s.appointmentStatusEnum.enumValues)[number];
export type ActivityType = (typeof s.activityTypeEnum.enumValues)[number];
export type Intent = (typeof s.intentEnum.enumValues)[number];
export type LeadTemperature = (typeof s.leadTemperatureEnum.enumValues)[number];
export type AgentType = (typeof s.agentTypeEnum.enumValues)[number];
export type JobStatus = (typeof s.jobStatusEnum.enumValues)[number];
export type SuppressionReason = (typeof s.suppressionReasonEnum.enumValues)[number];
export type ProviderKind = (typeof s.providerKindEnum.enumValues)[number];
export type NotificationType = (typeof s.notificationTypeEnum.enumValues)[number];
export type MembershipStatus = (typeof s.membershipStatusEnum.enumValues)[number];

export const PROSPECT_STATUSES = s.prospectStatusEnum.enumValues;
export const CONVERSATION_STATES = s.conversationStateEnum.enumValues;
export const PIPELINE_STAGES = s.pipelineStageEnum.enumValues;
export const CAMPAIGN_STATUSES = s.campaignStatusEnum.enumValues;
export const USER_ROLES = s.userRoleEnum.enumValues;
